
package Jframe;

import Jframe.DBConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class IssueBook extends javax.swing.JFrame {


    public IssueBook() {
        initComponents();

    }
public void getBookDetails() {
    int bookId = Integer.parseInt(txt_book1.getText());

    try {
       Connection con = DBConnection.getConnection();

        PreparedStatement pst = con.prepareStatement(
            "SELECT * FROM book_details WHERE book_id = ?"
        );
        pst.setInt(1, bookId); 
     ResultSet rs = pst.executeQuery();

        if (rs.next()) {
           bookid.setText(rs.getString("book_id"));
            bookname.setText(rs.getString("book_name"));
          bookauthor.setText(rs.getString("author"));
            bookquantity.setText(rs.getString("quantity"));
        } else {
            System.out.println("No book found with the given ID.");
        }

    } catch (Exception e) {
       e.printStackTrace();
    }
}



public void getStudentDetails() {
    int student_id = Integer.parseInt(txt_student.getText());

    try {
       Connection con = DBConnection.getConnection();

        PreparedStatement pst = con.prepareStatement(
            "SELECT * FROM student_details WHERE student_id = ?"
        );
        pst.setInt(1, student_id); 
     ResultSet rs = pst.executeQuery();

        if (rs.next()) {
           student_id.setText(rs.getString("studentid"));
            studentName.setText(rs.getString("studentName"));
          course.setText(rs.getString("studentcourse"));
            branch.setText(rs.getString("studentbranch1"));
        } else {
            System.out.println("No student found with the given ID.");
        }

    } catch (Exception e) {
       e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        bookname = new javax.swing.JTextField();
        bookauthor = new javax.swing.JTextField();
        bookquantity = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        studentcourse = new javax.swing.JTextField();
        studentbranch1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        txt_student = new javax.swing.JTextField();
        txt_book1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 0, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\abesi\\OneDrive\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\resources\\icons8_Rewind_48px.png")); // NOI18N
        jLabel3.setText("Back");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 185, 380, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Book Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Author :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Book   Id :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\abesi\\OneDrive\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\resources\\icons8_Literature_100px_1.png")); // NOI18N
        jLabel4.setText("    Book Details ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 240, 100));

        bookid.setBackground(new java.awt.Color(204, 255, 255));
        bookid.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        bookid.setToolTipText("");
        bookid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bookid.setName(""); // NOI18N
        jPanel1.add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 370, 40));

        bookname.setBackground(new java.awt.Color(204, 255, 255));
        bookname.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        bookname.setToolTipText("");
        bookname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bookname.setName(""); // NOI18N
        jPanel1.add(bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 370, 40));

        bookauthor.setBackground(new java.awt.Color(204, 255, 255));
        bookauthor.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        bookauthor.setToolTipText("");
        bookauthor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bookauthor.setName(""); // NOI18N
        jPanel1.add(bookauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 370, 40));

        bookquantity.setBackground(new java.awt.Color(204, 255, 255));
        bookquantity.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        bookquantity.setToolTipText("");
        bookquantity.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bookquantity.setName(""); // NOI18N
        bookquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookquantityActionPerformed(evt);
            }
        });
        jPanel1.add(bookquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 370, 40));

        panel_main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 420, 740));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\abesi\\OneDrive\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\resources\\icons8_Student_Registration_100px_2.png")); // NOI18N
        jLabel12.setText("    Book Details ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 240, 100));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 185, 380, 5));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Branch :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 130, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Student Name:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 150, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Course:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 130, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Student   Id :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 30));

        studentName.setBackground(new java.awt.Color(204, 255, 255));
        studentName.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        studentName.setToolTipText("");
        studentName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        studentName.setName(""); // NOI18N
        jPanel3.add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 370, 40));

        studentid.setBackground(new java.awt.Color(204, 255, 255));
        studentid.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        studentid.setToolTipText("");
        studentid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        studentid.setName(""); // NOI18N
        jPanel3.add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 370, 40));

        studentcourse.setBackground(new java.awt.Color(204, 255, 255));
        studentcourse.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        studentcourse.setToolTipText("");
        studentcourse.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        studentcourse.setName(""); // NOI18N
        jPanel3.add(studentcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 370, 40));

        studentbranch1.setBackground(new java.awt.Color(204, 255, 255));
        studentbranch1.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        studentbranch1.setToolTipText("");
        studentbranch1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        studentbranch1.setName(""); // NOI18N
        studentbranch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentbranch1ActionPerformed(evt);
            }
        });
        jPanel3.add(studentbranch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 370, 40));

        panel_main.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 430, 740));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\abesi\\OneDrive\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\resources\\icons8_Books_52px_1.png")); // NOI18N
        jLabel1.setText("       Issue Book  ");
        panel_main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, 240, -1));

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));
        panel_main.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 370, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 204));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("X");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        panel_main.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 0, -1, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("Book   Id :");
        panel_main.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, 130, 30));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Student   Id :");
        panel_main.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 130, 30));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(255, 0, 0));
        rSMaterialButtonCircle3.setText("Issue  Book");
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        panel_main.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 690, 300, 60));

        txt_student.setBackground(new java.awt.Color(0, 0, 0));
        txt_student.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        txt_student.setForeground(new java.awt.Color(255, 255, 255));
        txt_student.setToolTipText("");
        txt_student.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txt_student.setName(""); // NOI18N
        txt_student.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentFocusLost(evt);
            }
        });
        txt_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentActionPerformed(evt);
            }
        });
        panel_main.add(txt_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 570, 370, 40));

        txt_book1.setBackground(new java.awt.Color(0, 0, 0));
        txt_book1.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        txt_book1.setForeground(new java.awt.Color(255, 255, 255));
        txt_book1.setToolTipText("");
        txt_book1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txt_book1.setName(""); // NOI18N
        panel_main.add(txt_book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 370, 40));

        jPanel6.setBackground(new java.awt.Color(0, 102, 51));
        panel_main.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 0, 240, 820));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 1350, 830));

        setSize(new java.awt.Dimension(1373, 773));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
      
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    private void bookquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookquantityActionPerformed

    private void txt_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentActionPerformed

    private void txt_studentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentFocusLost
      getBookDetails();  // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentFocusLost

    private void studentbranch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentbranch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentbranch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookauthor;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bookname;
    private javax.swing.JTextField bookquantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panel_main;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private javax.swing.JTextField studentName;
    private javax.swing.JTextField studentbranch1;
    private javax.swing.JTextField studentcourse;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField txt_book1;
    private javax.swing.JTextField txt_student;
    // End of variables declaration//GEN-END:variables
}
